# Generated by Django 5.2.3 on 2025-06-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campregistration',
            name='mobile',
        ),
    ]
