# Generated by Django 5.2.3 on 2025-06-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_donationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='donation_type',
        ),
    ]
