# Generated by Django 5.2.3 on 2025-06-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_donationhistory_donation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationHistory',
        ),
    ]
