# Generated by Django 5.2.3 on 2025-06-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emergencyrequest')),
            ],
            options={
                'unique_together': {('receiver', 'donor')},
            },
        ),
        migrations.DeleteModel(
            name='SuggestionHistory',
        ),
    ]
