# Generated by Django 5.2.3 on 2025-06-30 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_suggesteddonor_delete_suggestionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_donor_name', models.CharField(max_length=255)),
                ('suggested_donor_mobile', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=255)),
                ('date_suggested', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
