# Generated by Django 5.2.3 on 2025-06-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_suggestionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='emergency',
        ),
    ]
