# Generated by Django 5.2.3 on 2025-06-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_emergencyrequest_emergency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestionHistory',
        ),
    ]
