# Generated by Django 5.2.3 on 2025-06-30 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_suggestionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='emergency_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emergencyrequest'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
