# Generated by Django 5.2.3 on 2025-06-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment_emergency_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='emergency_profile',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmergencyAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodcenter')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emergencyrequest')),
            ],
        ),
    ]
