# Generated by Django 5.2.3 on 2025-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_appointment_emergency_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
