# Generated by Django 5.2.3 on 2025-06-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_otp_userprofile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
